version: "3"
services:
  api:
    image: ecommerce-api
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      MONGODB_DATABASE: ecommerce
      REDIS_URI: redis:6379
    ports:
      - 5000:5000
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "ecommerce-api"

  redis:
    image: redis
    ports:
      - 6379:6379


  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  
  prometheus:
    image: prom/prometheus:v2.27.0
    volumes:
      - ./jobs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: always
  
  grafana:
    image: grafana/grafana:7.5.6
    ports:
      - 3000:3000
    restart: always
  
  telegraf:
    image: telegraf:latest
    volumes: 
    - ./telegraf.conf:/etc/telegraf/telegraf.conf
    - /var/run/docker.sock:/var/run/docker.sock

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.1
    command: logstash -f /etc/logstash/logstash.conf
    volumes:
      - ./logs/logstash.conf:/etc/logstash/logstash.conf
    ports:
      - "5100:5100"
      - "12201:12201"
      - "12201:12201/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  
