version: "3.9"
services:
  api:
    image: ecommerce-api
    environment:
      MONGODB_URI: mongodb://mongodb:27017/
      MONGODB_DATABASE: ecommerce
      REDIS_URI: redis:6379
    external_links:
      - mongodb
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379


  mongodb:
    image: mongo:4.4.3
    ports:
      - 27017:27017

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api