version: 2.1

executors:
  environment:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/rabbice/ecommerce

jobs:
  test:
    executor: environment
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "go/pkg/mod"
      - run:
          name: Code linting
          command: >
            go get -u golang.org/x/lint/golint
            #golint ./...

workflows:
  ci_cd:
    jobs:
      - test
